// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lunar/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_574f0a8636587684, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_574f0a8636587684, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetLunarRequest struct {
	Yyyymmdd uint64 `protobuf:"varint,1,opt,name=yyyymmdd,proto3" json:"yyyymmdd,omitempty"`
}

func (m *QueryGetLunarRequest) Reset()         { *m = QueryGetLunarRequest{} }
func (m *QueryGetLunarRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetLunarRequest) ProtoMessage()    {}
func (*QueryGetLunarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_574f0a8636587684, []int{2}
}
func (m *QueryGetLunarRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLunarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLunarRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLunarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLunarRequest.Merge(m, src)
}
func (m *QueryGetLunarRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLunarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLunarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLunarRequest proto.InternalMessageInfo

func (m *QueryGetLunarRequest) GetYyyymmdd() uint64 {
	if m != nil {
		return m.Yyyymmdd
	}
	return 0
}

type QueryGetLunarResponse struct {
	Lunar Lunar `protobuf:"bytes,1,opt,name=lunar,proto3" json:"lunar"`
}

func (m *QueryGetLunarResponse) Reset()         { *m = QueryGetLunarResponse{} }
func (m *QueryGetLunarResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetLunarResponse) ProtoMessage()    {}
func (*QueryGetLunarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_574f0a8636587684, []int{3}
}
func (m *QueryGetLunarResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLunarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLunarResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLunarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLunarResponse.Merge(m, src)
}
func (m *QueryGetLunarResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLunarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLunarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLunarResponse proto.InternalMessageInfo

func (m *QueryGetLunarResponse) GetLunar() Lunar {
	if m != nil {
		return m.Lunar
	}
	return Lunar{}
}

type QueryAllLunarRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllLunarRequest) Reset()         { *m = QueryAllLunarRequest{} }
func (m *QueryAllLunarRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllLunarRequest) ProtoMessage()    {}
func (*QueryAllLunarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_574f0a8636587684, []int{4}
}
func (m *QueryAllLunarRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllLunarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllLunarRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllLunarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllLunarRequest.Merge(m, src)
}
func (m *QueryAllLunarRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllLunarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllLunarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllLunarRequest proto.InternalMessageInfo

func (m *QueryAllLunarRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllLunarResponse struct {
	Lunar      []Lunar             `protobuf:"bytes,1,rep,name=lunar,proto3" json:"lunar"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllLunarResponse) Reset()         { *m = QueryAllLunarResponse{} }
func (m *QueryAllLunarResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllLunarResponse) ProtoMessage()    {}
func (*QueryAllLunarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_574f0a8636587684, []int{5}
}
func (m *QueryAllLunarResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllLunarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllLunarResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllLunarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllLunarResponse.Merge(m, src)
}
func (m *QueryAllLunarResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllLunarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllLunarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllLunarResponse proto.InternalMessageInfo

func (m *QueryAllLunarResponse) GetLunar() []Lunar {
	if m != nil {
		return m.Lunar
	}
	return nil
}

func (m *QueryAllLunarResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAuspiciousRequest struct {
	Date       uint64             `protobuf:"varint,1,opt,name=date,proto3" json:"date,omitempty"`
	Auspicious string             `protobuf:"bytes,2,opt,name=auspicious,proto3" json:"auspicious,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAuspiciousRequest) Reset()         { *m = QueryAuspiciousRequest{} }
func (m *QueryAuspiciousRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAuspiciousRequest) ProtoMessage()    {}
func (*QueryAuspiciousRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_574f0a8636587684, []int{6}
}
func (m *QueryAuspiciousRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuspiciousRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuspiciousRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuspiciousRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuspiciousRequest.Merge(m, src)
}
func (m *QueryAuspiciousRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuspiciousRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuspiciousRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuspiciousRequest proto.InternalMessageInfo

func (m *QueryAuspiciousRequest) GetDate() uint64 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *QueryAuspiciousRequest) GetAuspicious() string {
	if m != nil {
		return m.Auspicious
	}
	return ""
}

func (m *QueryAuspiciousRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAuspiciousResponse struct {
	Lunar      []Lunar             `protobuf:"bytes,1,rep,name=lunar,proto3" json:"lunar"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAuspiciousResponse) Reset()         { *m = QueryAuspiciousResponse{} }
func (m *QueryAuspiciousResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAuspiciousResponse) ProtoMessage()    {}
func (*QueryAuspiciousResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_574f0a8636587684, []int{7}
}
func (m *QueryAuspiciousResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAuspiciousResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAuspiciousResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAuspiciousResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAuspiciousResponse.Merge(m, src)
}
func (m *QueryAuspiciousResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAuspiciousResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAuspiciousResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAuspiciousResponse proto.InternalMessageInfo

func (m *QueryAuspiciousResponse) GetLunar() []Lunar {
	if m != nil {
		return m.Lunar
	}
	return nil
}

func (m *QueryAuspiciousResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "zodiatic.zodiatic.lunar.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "zodiatic.zodiatic.lunar.QueryParamsResponse")
	proto.RegisterType((*QueryGetLunarRequest)(nil), "zodiatic.zodiatic.lunar.QueryGetLunarRequest")
	proto.RegisterType((*QueryGetLunarResponse)(nil), "zodiatic.zodiatic.lunar.QueryGetLunarResponse")
	proto.RegisterType((*QueryAllLunarRequest)(nil), "zodiatic.zodiatic.lunar.QueryAllLunarRequest")
	proto.RegisterType((*QueryAllLunarResponse)(nil), "zodiatic.zodiatic.lunar.QueryAllLunarResponse")
	proto.RegisterType((*QueryAuspiciousRequest)(nil), "zodiatic.zodiatic.lunar.QueryAuspiciousRequest")
	proto.RegisterType((*QueryAuspiciousResponse)(nil), "zodiatic.zodiatic.lunar.QueryAuspiciousResponse")
}

func init() { proto.RegisterFile("lunar/query.proto", fileDescriptor_574f0a8636587684) }

var fileDescriptor_574f0a8636587684 = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x94, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x73, 0x6d, 0x12, 0x95, 0xc7, 0xc4, 0x23, 0x50, 0x64, 0x21, 0xa7, 0x78, 0x68, 0xa1,
	0x05, 0x1f, 0x09, 0x03, 0x02, 0x09, 0xa1, 0x56, 0x88, 0x2e, 0x0c, 0x25, 0x30, 0x31, 0x20, 0x5d,
	0x92, 0x93, 0xb1, 0xe4, 0xf8, 0xdc, 0xd8, 0x46, 0x98, 0x28, 0x0b, 0x33, 0x03, 0x08, 0x16, 0x24,
	0xc4, 0x67, 0xe0, 0x63, 0x74, 0xac, 0xc4, 0xc2, 0x84, 0x50, 0xc2, 0x97, 0x60, 0x43, 0xb9, 0xbb,
	0xc4, 0x89, 0x83, 0x9b, 0xc0, 0xd4, 0xc5, 0xba, 0x5c, 0xfe, 0xef, 0xfd, 0x7f, 0x7e, 0x77, 0x7f,
	0xc3, 0x39, 0x2f, 0xf6, 0x59, 0x97, 0x1e, 0xc6, 0xbc, 0x9b, 0xd8, 0x41, 0x57, 0x44, 0x02, 0xd7,
	0x5f, 0x8b, 0xb6, 0xcb, 0x22, 0xb7, 0x65, 0x4f, 0x16, 0x52, 0x64, 0x54, 0x1c, 0xe1, 0x08, 0xa9,
	0xa1, 0xa3, 0x95, 0x92, 0x1b, 0x97, 0x1d, 0x21, 0x1c, 0x8f, 0x53, 0x16, 0xb8, 0x94, 0xf9, 0xbe,
	0x88, 0x58, 0xe4, 0x0a, 0x3f, 0xd4, 0xff, 0x6e, 0xb7, 0x44, 0xd8, 0x11, 0x21, 0x6d, 0xb2, 0x90,
	0x2b, 0x17, 0xfa, 0xb2, 0xd6, 0xe4, 0x11, 0xab, 0xd1, 0x80, 0x39, 0xae, 0x2f, 0xc5, 0x5a, 0x8b,
	0x8a, 0x25, 0x60, 0x5d, 0xd6, 0x19, 0xd7, 0x6b, 0x3e, 0xf9, 0x54, 0x5b, 0x56, 0x05, 0xf0, 0xf1,
	0xa8, 0xd1, 0x81, 0xd4, 0x35, 0xf8, 0x61, 0xcc, 0xc3, 0xc8, 0x7a, 0x0a, 0xe7, 0x67, 0x76, 0xc3,
	0x40, 0xf8, 0x21, 0xc7, 0x7b, 0x50, 0x56, 0xfd, 0x2e, 0x91, 0x0d, 0x72, 0xf5, 0x6c, 0xbd, 0x6a,
	0xe7, 0xbc, 0x9d, 0xad, 0x0a, 0xf7, 0x8a, 0x47, 0x3f, 0xaa, 0x85, 0x86, 0x2e, 0xb2, 0xea, 0x50,
	0x91, 0x5d, 0xf7, 0x79, 0xf4, 0x68, 0xa4, 0xd2, 0x6e, 0x68, 0xc0, 0x5a, 0x92, 0x24, 0x49, 0xa7,
	0xd3, 0x6e, 0xcb, 0xc6, 0xc5, 0xc6, 0xe4, 0xb7, 0xf5, 0x04, 0x2e, 0x64, 0x6a, 0x34, 0xcb, 0x5d,
	0x28, 0x49, 0x2b, 0x8d, 0x62, 0xe6, 0xa2, 0xc8, 0x32, 0x4d, 0xa2, 0x4a, 0xac, 0xe7, 0x1a, 0x64,
	0xd7, 0xf3, 0x66, 0x40, 0x1e, 0x02, 0xa4, 0x73, 0xd4, 0x8d, 0x37, 0x6d, 0x35, 0x74, 0x7b, 0x34,
	0x74, 0x5b, 0x1d, 0xad, 0x1e, 0xba, 0x7d, 0xc0, 0x1c, 0xae, 0x6b, 0x1b, 0x53, 0x95, 0xd6, 0x67,
	0xa2, 0xa9, 0x53, 0x83, 0x79, 0xea, 0xd5, 0x7f, 0xa4, 0xc6, 0xfd, 0x19, 0xba, 0x15, 0x49, 0xb7,
	0xb5, 0x90, 0x4e, 0x19, 0xcf, 0xe0, 0x7d, 0x24, 0x70, 0x51, 0xe1, 0xc5, 0x61, 0xe0, 0xb6, 0x5c,
	0x11, 0x8f, 0x0f, 0x1e, 0x11, 0x8a, 0x6d, 0x16, 0x71, 0x7d, 0x0c, 0x72, 0x8d, 0x26, 0x00, 0x9b,
	0x08, 0xa5, 0xef, 0x99, 0xc6, 0xd4, 0x4e, 0x66, 0x6a, 0xab, 0xff, 0x3d, 0xb5, 0x2f, 0x04, 0xd6,
	0xe7, 0xb0, 0x4e, 0xd1, 0xdc, 0xea, 0xbf, 0x8b, 0x50, 0x92, 0x80, 0xf8, 0x96, 0x40, 0x59, 0x5d,
	0x71, 0xdc, 0xc9, 0x45, 0x99, 0xcf, 0x95, 0x71, 0x7d, 0x39, 0xb1, 0xf2, 0xb6, 0xb6, 0xde, 0x7c,
	0xfb, 0xf5, 0x61, 0xe5, 0x0a, 0x56, 0xe9, 0x58, 0x9c, 0x2e, 0xa6, 0xd3, 0x8d, 0x9f, 0x08, 0x94,
	0xe4, 0x8b, 0xe3, 0x8d, 0x93, 0x0d, 0x32, 0xc9, 0x33, 0xec, 0x65, 0xe5, 0x9a, 0xa8, 0x26, 0x89,
	0x76, 0xf0, 0x5a, 0x2e, 0x91, 0x7a, 0xf6, 0xc6, 0xf9, 0xed, 0xe3, 0x7b, 0x02, 0x6b, 0xb2, 0xc9,
	0xae, 0xe7, 0x2d, 0xc2, 0xcb, 0xe4, 0x71, 0x11, 0x5e, 0x36, 0x5d, 0xd6, 0xa6, 0xc4, 0xdb, 0x40,
	0xf3, 0x64, 0x3c, 0xfc, 0x4a, 0x00, 0xd2, 0x4b, 0x86, 0x74, 0x81, 0x4d, 0x36, 0x25, 0xc6, 0xcd,
	0xe5, 0x0b, 0x34, 0xd9, 0x7d, 0x49, 0x76, 0x07, 0x6f, 0xe7, 0x92, 0xa5, 0x81, 0xa2, 0xbd, 0x51,
	0xec, 0xfa, 0xb4, 0x97, 0x6e, 0xf5, 0xf7, 0x1e, 0x1c, 0x0d, 0x4c, 0x72, 0x3c, 0x30, 0xc9, 0xcf,
	0x81, 0x49, 0xde, 0x0d, 0xcd, 0xc2, 0xf1, 0xd0, 0x2c, 0x7c, 0x1f, 0x9a, 0x85, 0x67, 0xdb, 0x8e,
	0x1b, 0xbd, 0x88, 0x9b, 0x76, 0x4b, 0x74, 0xfe, 0xd2, 0xfc, 0x95, 0x6e, 0x1f, 0x25, 0x01, 0x0f,
	0x9b, 0x65, 0xf9, 0xd1, 0xbf, 0xf5, 0x27, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x36, 0xcf, 0x7a, 0xa9,
	0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a Lunar by index.
	Lunar(ctx context.Context, in *QueryGetLunarRequest, opts ...grpc.CallOption) (*QueryGetLunarResponse, error)
	// Queries a list of Lunar items.
	LunarAll(ctx context.Context, in *QueryAllLunarRequest, opts ...grpc.CallOption) (*QueryAllLunarResponse, error)
	// Queries a list of Auspicious items.
	Auspicious(ctx context.Context, in *QueryAuspiciousRequest, opts ...grpc.CallOption) (*QueryAuspiciousResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/zodiatic.zodiatic.lunar.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Lunar(ctx context.Context, in *QueryGetLunarRequest, opts ...grpc.CallOption) (*QueryGetLunarResponse, error) {
	out := new(QueryGetLunarResponse)
	err := c.cc.Invoke(ctx, "/zodiatic.zodiatic.lunar.Query/Lunar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LunarAll(ctx context.Context, in *QueryAllLunarRequest, opts ...grpc.CallOption) (*QueryAllLunarResponse, error) {
	out := new(QueryAllLunarResponse)
	err := c.cc.Invoke(ctx, "/zodiatic.zodiatic.lunar.Query/LunarAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Auspicious(ctx context.Context, in *QueryAuspiciousRequest, opts ...grpc.CallOption) (*QueryAuspiciousResponse, error) {
	out := new(QueryAuspiciousResponse)
	err := c.cc.Invoke(ctx, "/zodiatic.zodiatic.lunar.Query/Auspicious", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a Lunar by index.
	Lunar(context.Context, *QueryGetLunarRequest) (*QueryGetLunarResponse, error)
	// Queries a list of Lunar items.
	LunarAll(context.Context, *QueryAllLunarRequest) (*QueryAllLunarResponse, error)
	// Queries a list of Auspicious items.
	Auspicious(context.Context, *QueryAuspiciousRequest) (*QueryAuspiciousResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Lunar(ctx context.Context, req *QueryGetLunarRequest) (*QueryGetLunarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lunar not implemented")
}
func (*UnimplementedQueryServer) LunarAll(ctx context.Context, req *QueryAllLunarRequest) (*QueryAllLunarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LunarAll not implemented")
}
func (*UnimplementedQueryServer) Auspicious(ctx context.Context, req *QueryAuspiciousRequest) (*QueryAuspiciousResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auspicious not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zodiatic.zodiatic.lunar.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Lunar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetLunarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Lunar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zodiatic.zodiatic.lunar.Query/Lunar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Lunar(ctx, req.(*QueryGetLunarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LunarAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllLunarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LunarAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zodiatic.zodiatic.lunar.Query/LunarAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LunarAll(ctx, req.(*QueryAllLunarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Auspicious_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAuspiciousRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Auspicious(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zodiatic.zodiatic.lunar.Query/Auspicious",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Auspicious(ctx, req.(*QueryAuspiciousRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zodiatic.zodiatic.lunar.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Lunar",
			Handler:    _Query_Lunar_Handler,
		},
		{
			MethodName: "LunarAll",
			Handler:    _Query_LunarAll_Handler,
		},
		{
			MethodName: "Auspicious",
			Handler:    _Query_Auspicious_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lunar/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetLunarRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLunarRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLunarRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Yyyymmdd != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Yyyymmdd))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetLunarResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLunarResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLunarResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Lunar.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllLunarRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllLunarRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllLunarRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllLunarResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllLunarResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllLunarResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Lunar) > 0 {
		for iNdEx := len(m.Lunar) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Lunar[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryAuspiciousRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuspiciousRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuspiciousRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Auspicious) > 0 {
		i -= len(m.Auspicious)
		copy(dAtA[i:], m.Auspicious)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Auspicious)))
		i--
		dAtA[i] = 0x12
	}
	if m.Date != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Date))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryAuspiciousResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAuspiciousResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAuspiciousResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Lunar) > 0 {
		for iNdEx := len(m.Lunar) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Lunar[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetLunarRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Yyyymmdd != 0 {
		n += 1 + sovQuery(uint64(m.Yyyymmdd))
	}
	return n
}

func (m *QueryGetLunarResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Lunar.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllLunarRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllLunarResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Lunar) > 0 {
		for _, e := range m.Lunar {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAuspiciousRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Date != 0 {
		n += 1 + sovQuery(uint64(m.Date))
	}
	l = len(m.Auspicious)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAuspiciousResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Lunar) > 0 {
		for _, e := range m.Lunar {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLunarRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLunarRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLunarRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Yyyymmdd", wireType)
			}
			m.Yyyymmdd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Yyyymmdd |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLunarResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLunarResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLunarResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lunar", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Lunar.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllLunarRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllLunarRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllLunarRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllLunarResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllLunarResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllLunarResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lunar", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lunar = append(m.Lunar, Lunar{})
			if err := m.Lunar[len(m.Lunar)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuspiciousRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuspiciousRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuspiciousRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Date", wireType)
			}
			m.Date = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Date |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Auspicious", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Auspicious = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAuspiciousResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAuspiciousResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAuspiciousResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lunar", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lunar = append(m.Lunar, Lunar{})
			if err := m.Lunar[len(m.Lunar)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
